name: 'release'
description: 'Automated release management with changelog generation and version bumping based on Conventional Commits'
author: 'oljc'

branding:
  icon: "tag"
  color: "black"

inputs:
  token:
    description: 'GitHub token for authentication'
    required: true
  
  version-file:
    description: 'Path to version file (package.json or plain text)'
    required: false
    default: 'package.json'
  
  changelog-file:
    description: 'Path to changelog file'
    required: false
    default: 'CHANGELOG.md'
  
  branch:
    description: 'Target branch for release PR'
    required: false
    default: 'main'
  
  branch-prefix:
    description: 'Prefix for release branch name'
    required: false
    default: 'release-'
  
  version-bump:
    description: 'Version bump strategy: auto (detect from commits), major, minor, patch'
    required: false
    default: 'auto'
  
  channel:
    description: 'Release channel: alpha, beta, rc, or latest (auto-calculated stable version)'
    required: false
    default: 'latest'
  
  tag-prefix:
    description: 'Prefix for version tags'
    required: false
    default: 'v'

outputs:
  pr:
    description: 'Release PR number or merged PR number'
  
  version:
    description: 'Version number (new or current)'
  
  published:
    description: 'Whether the release was published (true) or PR was created (false)'

runs:
  using: 'node20'
  main: 'dist/index.js'

